### ISSUE TITLE
Warning sign on rounded image.

### ISSUE THREAD

**Issue by crejer** [estevez-dev/extended-banner-card#4]
Hi,

first of all, great card!!

When using a `image:true` in the card with i get a warning sign on top of the rendered image.
Any idea why this is happening?

![Screenshot 2021-05-18 at 17 10 10](https://user-images.githubusercontent.com/2621483/118676920-1a8caa80-b7fc-11eb-97ed-39a817c901ae.png)

My config:
``` 
type: 'custom:extended-banner-card'
row_size: 2
header:
  title:
    - Badkamer
entities:
  - entity: media_player.badkamer
    name: Sonos
    attribute: entity_picture
    image: true
    size: 4
  - entity: media_player.badkamer
    name: Nummer
    attribute: media_title
    size: 2
  - entity: media_player.badkamer
    name: Artist
    attribute: media_artist
  - entity: media_player.badkamer
    name: Kanaal
    attribute: media_channel
```

The value of the `entity_picture` attribute is `/api/media_player_proxy/media_player.badkamer?token=*****&cache=*****`
